### PR TITLE
test: add a ci action

### PR DESCRIPTION
**Pull request by adnanjpg**
this action will run on each push & pr and verify if it builds correctly and does not break the tests

### CODE REVIEW

**Comment by adnanjpg** [comment]
cache also seems to work perfectly, the first action runs in 3m 12s while the second only takes 41s

**Comment by adnanjpg** [comment]
@isaidsari the current CI runs on each push and runs on an ubuntu machine. do u think we should also let this run on macOS & Windows? 
or maybe keep the ubuntu CI run on each push, and run macOS and Windows CI's on PR's?

**Comment by isaidsari** [comment]
yeah, testing on others platforms would be nice

**Review by isaidsari — APPROVED** [review]
🤘

**Comment by adnanjpg** [comment]
ok so we're all set...
...or are we?
we're running fine for ubuntu, macos and windows all on x64, but there's so public ARM64 support on github actions.
this is fine for ubuntu and windows, as most servers run x64, but for macos lately there's a ton of servers that moved to ARM64 (with the m chips series), so that's a bummer
nothing we can do about this

**Pull request merged**
