### PR TITLE
simple grpc functionalty is added

### PR DESCRIPTION
**Pull request by isaidsari**
there are still parts to be work on, but i will complete it as soon as it settles in my mind.

### CODE REVIEW

**Comment by isaidsari** [comment]
as expected it failed paltform ci builds other than linux because lack of proto-compiler, i need to/will check them.

**Comment by adnanjpg** [comment]
why is ci failing @isaidsari ?

**Comment by isaidsari** [comment]
> why is ci failing @isaidsari ?

i was fixed the ubuntu run on previous commit that caused by lack of proto compiler used in build script. later i put some optional fields in proto file and it seems its an experimental feature so it complains for why i dont put some experimental feature allow flag.

**Comment by isaidsari** [comment]
> why is ci failing @isaidsari ?

not anymore

**Pull request merged**
